### ISSUE TITLE
How to add a VTH touch panel?

### ISSUE THREAD

**Issue by Cr4z33** [felipecrs/dahua-vto-on-home-assistant#3]
So I thought it was better opening a separate issue to not go off topic with the other issues.

Considering that I used your `extensions.conf` and `pjsip_custom.conf` for the VTO can you @felipecrs please tell me what to enter to add my VTH touch panel (lets say I give it SIP extension `9902`)?

So far I've edited its SIP server details to connect with the Asterisk integration.

**Comment by felipecrs** [comment]
I have really no idea, as I don't have nor plan to have a VTH.

![image](https://github.com/felipecrs/dahua-vto-on-home-assistant/assets/29582865/c8ea81e5-26f0-4a90-976e-ea679d3c360f)

I would suggest you try finding help in the Asterisk add-on repository or in their Discord:

https://discord.com/channels/912636682346582076/996826337727762463

That said, if you find a solution, I'd suggest you paste it back here in case others have the same doubt.

**Comment by Cr4z33** [comment]
Yeah basically I was merely asking how to add further extensions as whatever SIP device might do the job.

Shall I better ask in the Asterisk forums first? 🤔

**Comment by felipecrs** [comment]
> Yeah basically I was merely asking how to add further extensions as whatever SIP device might do the job.

If that's the case you can just copy whatever you did for 8001 and change the number.

> Shall I better ask in the Asterisk forums first? 🤔

I stand for my recommendations above. I don't think Asterisk forums are very helpful.
