### ISSUE TITLE
Tuya E14 RGB LED tz3210_ifga63rg_ts0505b not working with ZHA

### ISSUE THREAD

**Issue by rozsap** [felipecrs/dahua-vto-on-home-assistant#5]
You can't turn on the light bulb. No RGB, brightness interface.
There is no bulb with ID ifga63rg in the Blackadder database.
I only use ZHA so I can't say if it would work with Z2M.

**Comment by felipecrs** [comment]
@rozsap did you open this by mistake?

**Comment by rozsap** [comment]
Sorry, I didn't mean to go here.

**Comment by felipecrs** [comment]
I'm deleting it then. No problem.
